"""Media generation through one handle, with an explicit place to put bytes.

`MediaOutput` requires `dir=` or `store=`. Generated bytes have to live
somewhere, and guessing a temp directory on the user's behalf is how files go
missing -- so the API asks rather than assumes.
"""

from pathlib import Path

from _bench import api_key, bench, model

from combycode_llm_sdk import MediaOutput


def main() -> str:
    media = MediaOutput(
        model=model(),
        api_key=api_key(),
        dir=Path("./.media-out"),
    )
    images = media.generate_image(
        prompt="a red circle on white background",
        params={"size": "1024x1024"},
    )
    return str(images[0].meta.size if images else 0)


bench(main)
