"""Generating media, and putting the bytes somewhere.

`MediaOutput` is the one place that knows an asset has to be STORED. Adapters
parse bytes; this saves them, mints an id, and emits `onMediaGenerated` carrying
what the cost collector needs to price the batch. A caller gets a receipt, never
a payload -- which is why `generate_image` returns ids and not megabytes.

Video is the shape that justifies the class. It is asynchronous on every
provider: submit, then poll, then download. The polling loop lives here rather
than in each adapter so all four report progress the same way, and so a caller
waiting ten minutes for a clip gets `on_media_progress` events meanwhile.

This is the SEPARATE-endpoint path. Media that arrives inline in a completion --
a Gemini image part, OpenAI's image_generation tool -- is handled by the chat
adapters and never reaches this class.

Transposed from `unified-library-ts/src/plugins/media/output.ts`.
"""

from __future__ import annotations

import threading
import time
import uuid
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from .registry import media_adapter
from .stores import FileMediaStore
from .types import (
    MEDIA_OUTPUT_DEFAULTS,
    MediaMeta,
    MediaResult,
    MediaStore,
    MediaType,
    RawMediaResult,
    VideoStatus,
)

#: The id prefix per kind, so an id says what it is without a lookup.
_PREFIX: Mapping[str, str] = {"image": "img", "audio": "aud", "video": "vid"}


class MediaOutput:
    """Image, audio and video generation over separate provider endpoints.

        media = MediaOutput(model="openai/gpt-image-1", api_key=key, dir="./out")
        images = media.generate_image(prompt="a red circle")
        images[0].meta.size

    **`dir=` or `store=` is required.** Generated bytes have to live somewhere,
    and guessing a temp directory on the caller's behalf is how files go
    missing -- so the constructor asks rather than assumes.

    One handle is bound to ONE model, because that is how a caller thinks about
    it: an image handle and a speech handle are different objects even on the
    same provider.
    """

    def __init__(
        self,
        *,
        model: str = "",
        api_key: str | None = None,
        dir: str | Path | None = None,
        store: MediaStore | None = None,
        provider: str | None = None,
        base_url: str | None = None,
        engine: Any = None,
        transport: Any = None,
        fetch: Any = None,
        hooks: Any = None,
        adapters: Mapping[str, Any] | None = None,
        catalog: Any = None,
        poll_interval: float | None = None,
        max_poll_wait: float | None = None,
        session_id: str | None = None,
    ) -> None:
        if store is None and dir is None:
            raise ValueError(
                "MediaOutput needs somewhere to put the bytes: pass dir= for a "
                "directory on disk, or store= for your own MediaStore. Guessing a "
                "temp directory is how generated files go missing."
            )
        self._provider, self._model = _split_model(model, provider)
        self._fetch = fetch or _fetch(engine, transport)
        self.store: MediaStore = store or FileMediaStore(dir)  # type: ignore[arg-type]
        self._hooks = hooks if hooks is not None else getattr(engine, "hooks", None)
        self._adapters: dict[str, Any] = dict(adapters or {})
        if self._provider and self._provider not in self._adapters:
            key = api_key or (
                engine.api_keys.get(self._provider) if engine is not None else None
            )
            if not key:
                raise ValueError(
                    f'MediaOutput: no API key for provider "{self._provider}". '
                    "Pass api_key= or engine.api_keys."
                )
            self._adapters[self._provider] = media_adapter(self._provider, key, base_url)
        # From the engine when not given outright: without a catalog the
        # handle sends our slug verbatim, and a slug is not what the
        # provider answers to.
        self._catalog = catalog if catalog is not None else getattr(engine, "catalog", None)
        self._poll_interval = (
            poll_interval
            if poll_interval is not None
            else MEDIA_OUTPUT_DEFAULTS["poll_interval_seconds"]
        )
        self._max_poll_wait = (
            max_poll_wait
            if max_poll_wait is not None
            else MEDIA_OUTPUT_DEFAULTS["max_poll_wait_seconds"]
        )
        self._session_id = session_id
        #: Set to abandon a poll. An Event rather than a flag so `close()` need
        #: not wait out a five-second interval.
        self._stop = threading.Event()

    def register_adapter(self, name: str, adapter: Any) -> None:
        self._adapters[name] = adapter

    def close(self) -> None:
        """Stop any polling loop. Idempotent."""
        self._stop.set()

    # -- generation ----------------------------------------------------------

    def generate_image(
        self, *, prompt: str, params: Mapping[str, Any] | None = None
    ) -> list[MediaResult]:
        """One or more images. Always a LIST -- `n` is a provider parameter."""
        provider, model = self._route()
        adapter = self._adapter(provider, "image_generation")
        raw = adapter.generate_image(prompt, model, self._traced(), params)
        return self._save(raw, "image", provider, model, prompt, params)

    def edit_image(
        self,
        *,
        prompt: str,
        source_image: Mapping[str, Any],
        params: Mapping[str, Any] | None = None,
        mask: Mapping[str, Any] | None = None,
    ) -> list[MediaResult]:
        provider, model = self._route()
        adapter = self._adapter(provider, "image_editing")
        kwargs: dict[str, Any] = {}
        if mask is not None:
            kwargs["mask"] = mask
        raw = adapter.edit_image(prompt, source_image, model, self._traced(), params, **kwargs)
        return self._save(raw, "image", provider, model, prompt, params)

    def generate_audio(
        self, *, prompt: str, params: Mapping[str, Any] | None = None
    ) -> list[MediaResult]:
        """Speech. A LIST of one, so every generate_* returns the same shape.

        `params["voice"]` takes a unified alias -- `neutral`, `warm`, `bright`,
        `deep` -- resolved to each provider's own id by the wire spec. A
        provider's own voice name passes through untouched, so knowing the
        catalogue is never a disadvantage.
        """
        provider, model = self._route()
        adapter = self._adapter(provider, "audio_generation")
        raw = adapter.generate_audio(prompt, model, self._traced(), params)
        # The PROMPT for speech is the text that was spoken, which is what a
        # caller listing their assets needs to see.
        return self._save([raw], "audio", provider, model, prompt, params)

    def generate_video(
        self, *, prompt: str, params: Mapping[str, Any] | None = None
    ) -> list[MediaResult]:
        provider, model = self._route()
        adapter = self._adapter(provider, "video_generation")
        operation = adapter.submit_video(prompt, model, self._traced(), params)
        if not operation:
            raise RuntimeError(
                f"{provider} accepted the video request but returned no operation id, "
                "so there is nothing to poll."
            )
        return [self._await_video(adapter, operation, provider, model, prompt, params)]

    # -- internals -----------------------------------------------------------

    def _route(self) -> tuple[str, str]:
        """Which provider, and the model id that provider actually answers to.

        The translation is the same one `LLM`, embeddings, batch, realtime and
        transcription all do: our normalised slug is not always callable.
        `google/gemini-3.1-flash-tts` has to reach the wire as
        `gemini-3.1-flash-tts-preview`, and sending the slug is a 404 with our
        own spelling in it. An id the provider already accepts, and one we have
        never heard of, both pass through untouched.
        """
        if not self._provider:
            raise ValueError(
                'MediaOutput: name the provider, either as provider= or as '
                '"provider/model" in model=.'
            )
        if self._catalog is None or not self._model:
            return self._provider, self._model
        return self._provider, str(
            self._catalog.resolve_model_id(self._provider, self._model)
        )

    def _adapter(self, provider: str, capability: str) -> Any:
        adapter = self._adapters.get(provider)
        if adapter is None:
            raise ValueError(
                f"no media adapter registered for {provider!r}. "
                f"Registered: {', '.join(sorted(self._adapters)) or 'none'}."
            )
        # Asked BEFORE the request: a provider that cannot do this is refused
        # by name here rather than by a 404 from somewhere inside its API.
        if not getattr(adapter.capabilities(), capability, False):
            raise ValueError(f"{provider} does not support {capability.replace('_', ' ')}")
        return adapter

    def _traced(self) -> Any:
        """The fetch, with a request id stamped on every call this op makes."""
        trace = {"sessionId": self._session_id, "requestId": f"req_{uuid.uuid4().hex[:12]}"}

        def fetch(request: Mapping[str, Any], options: Any = None) -> Any:
            return self._fetch({**dict(request), "trace": trace}, options)

        return fetch

    def _save(
        self,
        raw_results: Sequence[RawMediaResult],
        media_type: MediaType,
        provider: str,
        model: str,
        prompt: str | None,
        params: Mapping[str, Any] | None,
    ) -> list[MediaResult]:
        results: list[MediaResult] = []
        for raw in raw_results:
            media_id = f"{_PREFIX[media_type]}_{uuid.uuid4().hex[:12]}"
            meta = MediaMeta(
                id=media_id,
                type=media_type,
                mime_type=raw.mime_type,
                size=len(raw.data),
                provider=provider,
                model=model or None,
                prompt=prompt,
                revised_prompt=raw.revised_prompt,
                width=raw.width,
                height=raw.height,
                duration_ms=raw.duration_ms,
                sample_rate=raw.sample_rate,
                params=dict(params) if params else None,
                source_url=raw.source_url,
            )
            self.store.save(media_id, raw.data, meta)
            results.append(
                MediaResult(id=media_id, type=media_type, mime_type=raw.mime_type, meta=meta)
            )

        # ONE event for the batch, not one per asset: a four-image request is
        # billed once, and four events would be priced four times.
        self._emit(
            "onMediaGenerated",
            {
                "parts": [
                    {"type": f"{media_type}_output", "mediaId": r.id, "mimeType": r.mime_type}
                    for r in results
                ],
                "stored": True,
                "provider": provider,
                "source": "media_output",
                "model": model or None,
                "mediaType": media_type,
                "count": len(results),
                "usage": _aggregate_usage(raw_results),
            },
        )
        return results

    def _await_video(
        self,
        adapter: Any,
        operation: str,
        provider: str,
        model: str,
        prompt: str,
        params: Mapping[str, Any] | None,
    ) -> MediaResult:
        fetch = self._traced()
        deadline = time.monotonic() + self._max_poll_wait
        while time.monotonic() < deadline and not self._stop.is_set():
            status: VideoStatus = adapter.get_video_status(operation, fetch)

            if status.status in ("pending", "processing"):
                # Emitted every poll so a caller can render a bar rather than
                # watch nothing for ten minutes.
                self._emit(
                    "onMediaProgress",
                    {
                        "type": "video",
                        "provider": provider,
                        "operationId": operation,
                        "progress": status.progress,
                        "model": model or None,
                    },
                )

            if status.status == "completed":
                raw = adapter.download_video(operation, fetch)
                return self._save([raw], "video", provider, model, prompt, params)[0]

            if status.status == "failed":
                self._emit(
                    "onMediaError",
                    {
                        "id": operation,
                        "type": "video",
                        "provider": provider,
                        "error": status.error or "video generation failed",
                        "operationId": operation,
                    },
                )
                raise RuntimeError(f"video generation failed: {status.error}")

            # Never sleeps past the deadline: a caller's timeout must mean what
            # it says even when the interval is longer than what is left.
            remaining = deadline - time.monotonic()
            if self._stop.wait(max(0.0, min(self._poll_interval, remaining))):
                break

        raise TimeoutError(
            f"video generation did not finish within {self._max_poll_wait:g}s "
            f"(operation {operation})"
        )

    def _emit(self, name: str, payload: Mapping[str, Any]) -> None:
        if self._hooks is not None:
            self._hooks.emit_sync(name, dict(payload))

    def __repr__(self) -> str:
        return f"<MediaOutput providers={sorted(self._adapters)}>"


def _aggregate_usage(raw_results: Sequence[RawMediaResult]) -> dict[str, int] | None:
    """Summed token usage, or None when nothing reported any.

    None rather than zeros: unit-priced media reports no tokens at all, and a
    zeroed usage would look like a token-priced call that happened to be free.
    """
    reported = [r.usage for r in raw_results if r.usage]
    if not reported:
        return None
    total: dict[str, int] = {}
    for usage in reported:
        for key, value in usage.items():
            if isinstance(value, int):
                total[key] = total.get(key, 0) + value
    return total


__all__ = ["MediaOutput"]


def _split_model(model: str, provider: str | None) -> tuple[str, str]:
    """`"openai/gpt-image-1"` into its two halves, or a bare model plus provider."""
    from ..helpers.client_resolver import is_namespaced_model_id, parse_model_id

    if model and is_namespaced_model_id(model):
        found, name = parse_model_id(model)
        return found or (provider or ""), name
    return provider or "", model


def _fetch(engine: Any, transport: Any) -> Any:
    """The engine's fetch, or a one-off on the same executor.

    Media is bytes and often large, but it goes through the SAME queue as a
    completion: a subsystem that reached the network its own way would be
    invisible to the rate limiter meant to keep the whole fleet under a
    provider's ceiling.
    """
    from ..bus.hook_bus import HookBus
    from ..network.executor import RequestExecutor
    from ..network.retry import DEFAULT_RETRY
    from ..transport import as_fetch, http_transport

    if engine is not None and transport is None:
        return engine.fetch

    send = as_fetch(transport or http_transport())
    executor = RequestExecutor(engine.hooks if engine is not None else HookBus())

    def fetch(req: Any, options: Any = None) -> Any:
        return executor.execute(req, lambda r: send(r), DEFAULT_RETRY)

    return fetch
